config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :attachments, only: %i[destroy]
  resources :subscriptions, only: %i[create destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]
  resources :votes, only: %i[create]
  resources :comments, only: %i[create]
  resources :oauth_email_confirmations, only: %i[new create]

  resources :searches, only: %i[index create] do
    get :result, on: :collection
  end

  resources :questions do
    resources :answers, shallow: true, except: %i[index show] do
      patch :pick_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new, edit] do
        resources :answers, shallow: true, except: %i[new, edit]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_users, through: :subscriptions, source: :user
  has_one :award, dependent: :destroy
  include Voteable
  include Commentable

  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :award, reject_if: :all_blank

  has_many_attached :files

  after_save { id = self.id }
  after_create :subscribe_author

  validates :title, :body, presence: true

  scope :created_today, -> { Question.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }

  private

  def subscribe_author
    user.subscribe(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  expose :questions, -> { Question.all }
  expose :question, -> { Question.find(params[:id]) }

  authorize_resource

  def index
    render json: questions
  end

  def show
    render json: question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      render json: @question, status: :created
    else
      render json: @question.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    if question.update(question_params)
      render json: question, status: :ok
    else
      render json: question.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    question.destroy
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  expose :questions, -> { Question.all }
  expose :question
  expose :answer, -> { Answer.new }

  after_action :publish_question, only: [:create]

  authorize_resource

  def new
    question.links.new
    question.build_award
  end

  def show
    answer.links.new
    @comment = Comment.new
    gon.question_author_id = question.user.id
    gon.question_id = question.id
  end

  def create
    @question = current_user.questions.create(question_params)
    if @question.save
      current_user.subscribe(@question)
      redirect_to @question, notice: "Your question successfully created."
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(question)
      if question.update(question_params)
        redirect_to question
      else
        render :edit
      end
    else
      render :edit, notice: "You're not an author of this question"
    end
  end

  def destroy
    if current_user.author_of?(question)
      question.destroy
      redirect_to questions_path, notice: 'Your question successfully deleted.'
    else
      render :show
    end
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/add_question',
        locals: { question: @question }
      )
    )
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [], links_attributes: [:name, :url],
                                     award_attributes: [:name, :image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_add_question.html.slim
h3 class='col-md-4' = link_to question.title, question_path(question)
p class='col-md-8' = question.body

app/views/questions/_question.html.slim
.offset-md-6
  h1= question.title
  h5= question.body

- if current_user && !current_user.author_of?(question)
  .offset-md-5
    = render partial: 'shared/votes', locals: { resource: question }

.offset-md-4
  = render partial: 'shared/links', locals: { resource: question }

.offset-md-4
  = render partial: 'shared/attached_files', locals: { resource: question }

.offset-md-4
  -if can? :subscribe, question
    - if current_user.subscribed?(question)
      .unsubscribe = link_to 'Unsubscribe', subscription_path(question), method: :delete, remote: true
    -else
      .subscribe = link_to 'Subscribe', subscriptions_path(question), method: :post, remote: true
    .subscribe-notification

  div class='row offset-md-6'
    p class='col-md-4' = 'Award available!' if question.award.present?
    - if current_user&.author_of?(question)
      p class='col-md-4' = link_to 'Delete question', question, method: :delete
      p class='col-md-4' = link_to 'Edit question', edit_question_path(question)

app/views/questions/edit.html.slim
= render 'shared/errors', resource: @question

= form_with model: question, local: true do |f|
  p
  = f.label :title
  = f.text_field :title
  p
  = f.label :body
  = f.text_area :body
  p
  = f.label :files
  = f.file_field :files, multiple: true
  p Links:
  p
    = f.fields_for :links do |link|
      = render 'links/nested_form', f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/nested_form'
  p= f.submit 'Save'

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path
p= link_to 'Search', searches_path

div class='row offset-md-2 col-md-10'
  h1 class='col-md-4' Question title
  h5 class='col-md-8' Question body

  -cache collection_cache_key_for :question do
    div class='row offset-md-2 col-md-10 questions-list'
      - questions.each do |question|
        h3 class='col-md-4' = link_to question.title, question_path(question)
        p class='col-md-8' = question.body

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: question, local: true do |f|
  p
  = f.label :title
  = f.text_field :title
  p
  = f.label :body
  = f.text_area :body
  p
  = f.label :files
  = f.file_field :files, multiple: true

  p Award for the best answer:
  p
    = f.fields_for :award do |a|
      p
        = a.label :name, 'Award name'
        = a.text_field :name
      p
        = a.label :image, 'Award image'
        = a.file_field :image

  p Links:
  p
    = f.fields_for :links do |link|
      = render 'links/nested_form', f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/nested_form'
  p= f.submit 'Ask'

app/views/questions/show.html.slim
- cache resource do
  .question
    = render question

  .best-answer-placeholder

  div class="comments-question-#{question.id}"
    p= render question.comments
  p= render template: 'comments/new', locals: { resource: question }

  .answers
    =render question.answers

  div class='answer-create offset-md-1'
    = render template: 'answers/new'

app/views/questions/subscribe.js.erb
$('.subscribe').html('<%= link_to "Unsubscribe", unsubscribe_question_path(question), method: :delete, remote: true %>');
$('.subscribe').addClass('unsubscribe');
$('.subscribe').removeClass('subscribe');
$('.subscribe-notification').html('Subscribed!');

app/views/questions/unsubscribe.js.erb
$('.unsubscribe').html('<%= link_to "Subscribe", subscribe_question_path(question), method: :post, remote: true %>');
$('.unsubscribe').addClass('subscribe');
$('.unsubscribe').removeClass('unsubscribe');
$('.subscribe-notification').html('Unsubscribed!');