config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :attachments, only: %i[destroy]
  resources :subscriptions, only: %i[create destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]
  resources :votes, only: %i[create]
  resources :comments, only: %i[create]
  resources :oauth_email_confirmations, only: %i[new create]

  resources :searches, only: %i[index create] do
    get :result, on: :collection
  end

  resources :questions do
    resources :answers, shallow: true, except: %i[index show] do
      patch :pick_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new, edit] do
        resources :answers, shallow: true, except: %i[new, edit]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def user_abilities
    guest_abilities
    can :create, :all
    cannot [:create, :update, :destroy], Award
    can [:update, :destroy], [Question, Answer], author_id: user.id
    can [:update, :destroy], Comment, user_id: user.id
    can [:update, :destroy], Link, linkable: { author_id: user.id }
    can :pick_best, Answer
    can :me, User, id: user.id
    cannot :pick_best, Answer, author_id: user.id
    can :subscribe, Question
    can :unsubscribe, Question, subscriptions: { user_id: user.id }
  end

  def admin_abilities
    can :manage, :all
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user
  include Voteable
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  has_many_attached :files

  validates :body, presence: true

  after_create :email_subscribers

  def choose_best
    previous_best = question.answers.find_by(best: true)
    ActiveRecord::Base.transaction do
      self.update!(best: true)
      user.awards << question.award if question.award.present?
      previous_best.update!(best: false) if previous_best
    end
  end

  private

  def email_subscribers
    SubscriptionJob.perform_later(question)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user, dependent: :destroy

  validates :provider, :uid, presence: true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  has_one_attached :image

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user, dependent: :destroy

  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validate :validate_link_url, on: :create
  validate :validate_link_url, on: :update

  URL_REGEXP = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix

  def to_gist?
    url.match?(/https:\/\/gist.github.com\/\w+\//)
  end

  private

  def validate_link_url
    errors.add(:url, 'Invalid url format') unless url.match?(URL_REGEXP)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribed_users, through: :subscriptions, source: :user
  has_one :award, dependent: :destroy
  include Voteable
  include Commentable

  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :award, reject_if: :all_blank

  has_many_attached :files

  after_save { id = self.id }
  after_create :subscribe_author

  validates :title, :body, presence: true

  scope :created_today, -> { Question.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }

  private

  def subscribe_author
    user.subscribe(self)
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github, :vkontakte]

  has_many :questions
  has_many :answers
  has_many :awards
  has_many :authorizations
  has_many :subscriptions

  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def author_of?(instance)
    self.id == instance.user_id
  end

  def self.find_for_oauth(auth)
    Services::FindForOauth.new(auth).call
  end

  def subscribe(question)
    subscriptions.create!(question: question) unless subscribed?(question)
  end

  def unsubscribe(question)
    subscriptions.find_by(question: question).destroy! if subscribed?(question)
  end

  def subscribed?(question)
    subscriptions.find_by(question_id: question).present?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voteable, polymorphic: true
  belongs_to :user

  validates :vote_type, inclusion: { in: [1, -1] }
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  expose :link

  authorize_resource

  def destroy
    if current_user&.author_of?(link.linkable)
      link.destroy
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s)
    "#{model.name.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    = include_gon
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/nav'
    = yield

app/views/shared/_attached_files.html.slim
.files
  - if resource.files.attached?
    - resource.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      - if current_user&.author_of?(resource)
        p= link_to 'Delete file', attachment_path(id: file.id), method: :delete, remote: true

app/views/shared/_cancan_exception.js.erb
$('.alert').html('<%= message %>');

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_links.html.slim
.links
  -resource.links.each do |link|
    p class="link-id-#{link.id}"
      -if link.to_gist?
        p= render partial: 'links/gist', locals: { link: link }
      -else
        p= link_to link.name, link.url
      p= link_to 'Delete link', link_path(id: link.id), method: :delete, remote: true, class: "delete-link"

app/views/shared/_nav.html.slim
div class='nav row text-center'
  p class='col-md-4 text-left' = link_to 'Home', questions_path
  p class="notice col-md-3" = notice
  p class="alert col-md-3" = alert
  - if user_signed_in?
    p class='col-md-1'= link_to 'Awards', awards_path
    p class='col-md-1' = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    p class='offset-md-1 col-md-1'= link_to 'Sign in', new_user_session_path

app/views/shared/_votes.html.slim
div class='row votes'
  p class='offset-md-1 col-md-1'
    = link_to 'Downvote', votes_path(vote: {vote_type: '-1',
                                     voteable_id: resource.id,
                                     voteable_type: resource.class.to_s  }),
                                     method: :post, remote: true, class: 'vote-link'

  p class='col-md-1 vote-result'
    = resource.vote_count

  p class='col-md-1'
    = link_to 'Upvote', votes_path(vote: { vote_type: '1',
                                   voteable_id: resource.id,
                                   voteable_type: resource.class.to_s }),
                                   method: :post, remote: true, class: 'vote-link'