config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :attachments, only: %i[destroy]
  resources :subscriptions, only: %i[create destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]
  resources :votes, only: %i[create]
  resources :comments, only: %i[create]
  resources :oauth_email_confirmations, only: %i[new create]

  resources :searches, only: %i[index create] do
    get :result, on: :collection
  end

  resources :questions do
    resources :answers, shallow: true, except: %i[index show] do
      patch :pick_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, except: %i[new, edit] do
        resources :answers, shallow: true, except: %i[new, edit]
      end
    end
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user
  include Voteable
  include Commentable

  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  has_many_attached :files

  validates :body, presence: true

  after_create :email_subscribers

  def choose_best
    previous_best = question.answers.find_by(best: true)
    ActiveRecord::Base.transaction do
      self.update!(best: true)
      user.awards << question.award if question.award.present?
      previous_best.update!(best: false) if previous_best
    end
  end

  private

  def email_subscribers
    SubscriptionJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  expose :question, -> { Question.find(params[:question_id]) }
  expose :answer

  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = question.answers.new(answer_params)
    @answer.author = current_user
    @answer.save
    @comment = Comment.new
  end

  def update
    if current_user.author_of?(answer)
      answer.update(answer_params)
    else
      redirect_to answer.question, notice: "You're not an author of this question"
    end
  end

  def destroy
    if current_user.author_of?(answer)
      @id = answer.id
      answer.destroy
    end
  end

  def pick_best
    if current_user.author_of?(question)
      authorize! :pick_best, answer
      answer.choose_best
    else
      redirect_to answer.question, notice: "You're not an author of this question"
    end
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("question_#{question.id}", @answer.to_json)
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  expose :question, -> { Question.find(params[:question_id]) }
  expose :answer, -> { Answer.find(params[:id]) }
  
  authorize_resource

  def index
    render json: question.answers
  end

  def show
    render json: answer
  end

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_resource_owner
    if @answer.save
      render json: @answer, status: :created
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    if answer.update(answer_params)
      render json: answer, status: :ok
    else
      render json: answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div data-answer-id='#{answer.id}' class='answer #{'best-answer' if answer.best?}'
    div class='row offset-md-1'
      p class="best-text #{'hidden' unless answer.best?}"
        ="Best answer: "
      p class='body'= "#{answer.body}"

    - if current_user && !current_user.author_of?(question)
      p= render partial: 'shared/votes', locals: { resource: answer }

    p= render partial: 'shared/links', locals: { resource: answer }

    p= render partial: 'shared/attached_files', locals: { resource: answer }

    - if current_user&.author_of?(answer)
      div class='offset-md-1'
        .row
          p class='col-md-1' = link_to 'Edit', '#', class: "edit-answer-link"

          p class='col-md-1' = link_to 'Delete', answer, method: :delete, remote: true, class: "delete-answer-link"

        div class='hidden edit-answer'
          p=render partial: 'answers/form', locals: { answer: answer, question: question }

    - if current_user&.author_of?(question)
      p class='offset-md-1 col-md-1' = link_to 'Pick as best', pick_best_answer_path(answer, question_id: question.id),
      class: "best-answer-link", method: :patch, remote: true

    div class="comments-answer-#{answer.id}"
      p= render answer.comments
    p= render template: 'comments/new', locals: { resource: answer }

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

.answer-form
  = form_with model: answer do |f|
    p
    = f.label :body, 'Body'
    = f.text_area :body
    p
    = f.label :files
    = f.file_field :files, multiple: true
    p Links:
    p
      = f.fields_for :links do |link|
        = render 'links/nested_form', f: link
      .links
        = link_to_add_association 'add link', f, :links, partial: 'links/nested_form'
    = f.submit 'Save'

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.answer-create #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$("div[data-answer-id='<%= @id %>']").remove();

app/views/answers/new.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

= form_with model: [question, answer] do |f|
  p
  = f.label :body
  = f.text_area :body
  p
  = f.label :files
  = f.file_field :files, multiple: true
  p Links:
  p
    = f.fields_for :links do |link|
      = render 'links/nested_form', f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'links/nested_form'
  = f.submit 'Answer'

app/views/answers/pick_best.js.erb
if ($('.best-answer').data('answerId') > 0) {
  var previousBestId = $('.best-answer').data('answerId');
  $('.best-answer').insertBefore('.answers');
  $('.best-answer .best-text').addClass('hidden');
  $('.best-answer').removeClass('best-answer');
};

var newBest = $('[data-answer-id=<%= answer.id %>]')
newBest.addClass('best-answer');
newBest.insertBefore('.best-answer-placeholder');
$('[data-answer-id=<%= answer.id %>] .best-text').removeClass('hidden')

app/views/answers/update.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: answer %>");

<% unless answer.errors.present? %>
  $('[data-answer-id="<%= answer.id %>"] .body').html('<p> <%= answer.body %> </p>');
  $("[data-answer-id=<%= answer.id%>] .edit-answer").addClass('hidden');
  $("[data-answer-id='<%= answer.id %>'] .edit-answer-link").removeClass('hidden');

  $('[data-answer-id="<%= answer.id %>"] .links').append('<%= render partial: "shared/links", locals: { resource: answer } %>');
  $('[data-answer-id="<%= answer.id %>"] .files').append('<%= render partial: "shared/attached_files", locals: { resource: answer } %>');
<% end %>